// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ata.Investment.Profile.Data;

namespace Ata.Investment.Profile.Data.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20200319200613_MeetingCompleteMigration")]
    partial class MeetingCompleteMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Investments")
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Household.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Household.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("JointClientId")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JointClientId");

                    b.HasIndex("PrimaryClientId");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("AdvisorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllocationVersion")
                        .HasColumnType("int");

                    b.Property<string>("CreatedFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateCompleted")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("KycDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Household.Household", b =>
                {
                    b.HasOne("Ata.Investment.Profile.Domain.Household.Client", "JointClient")
                        .WithMany()
                        .HasForeignKey("JointClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ata.Investment.Profile.Domain.Household.Client", "PrimaryClient")
                        .WithMany()
                        .HasForeignKey("PrimaryClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Meeting", b =>
                {
                    b.HasOne("Ata.Investment.Profile.Domain.Household.Household", "Household")
                        .WithMany("Meetings")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
