// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ata.Investment.Profile.Data;

#nullable disable

namespace Ata.Investment.Profile.Data.Migrations
{
    [DbContext(typeof(ProfileContext))]
    [Migration("20220211230357_MeetingSchedules")]
    partial class MeetingSchedules
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Investments")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Household.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("Name", "Email")
                        .IsUnique();

                    b.ToTable("Clients", "Investments");
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Household.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JointClientId")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JointClientId");

                    b.HasIndex("PrimaryClientId");

                    b.ToTable("Households", "Investments");
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("AdvisorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AllocationVersion")
                        .HasColumnType("int");

                    b.Property<string>("CreatedFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlKycDocumentSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KycDocument");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Meetings", "Investments");
                });

            modelBuilder.Entity("Ata.Investment.Schedule.Domain.MeetingSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("AdvisorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseholdId");

                    b.ToTable("Schedules", "Investments");
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Household.Household", b =>
                {
                    b.HasOne("Ata.Investment.Profile.Domain.Household.Client", "JointClient")
                        .WithMany()
                        .HasForeignKey("JointClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ata.Investment.Profile.Domain.Household.Client", "PrimaryClient")
                        .WithMany()
                        .HasForeignKey("PrimaryClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JointClient");

                    b.Navigation("PrimaryClient");
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Meeting", b =>
                {
                    b.HasOne("Ata.Investment.Profile.Domain.Household.Household", "Household")
                        .WithMany("Meetings")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Ata.Investment.Schedule.Domain.MeetingSchedule", b =>
                {
                    b.HasOne("Ata.Investment.Profile.Domain.Household.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Ata.Investment.Profile.Domain.Household.Household", b =>
                {
                    b.Navigation("Meetings");
                });
#pragma warning restore 612, 618
        }
    }
}
